Repository adtzlr/ttb, pull requests merged in 2023-07, with the labels that each got.

#42 Docs: Fix broken link to example 3
  docs/index.md
Labels: Documentation

#38 Enhance `libpower.f`, Fix `libassignscalar.f`
  CHANGELOG.md
  README.md
  docs/examples/script_umat.f
  docs/functions/power.md
  ttb/libassignscalar.f
  ttb/libpower.f
Labels: enhancement

#44 Fix cross-dyadic product: Ensure minor- and major-symmetric result
  CHANGELOG.md
  README.md
  docs/index.md
  docs/operators/operators_overview.md
  ttb/libcrossdyadic.f
  ttb/libidentity.f
  ttb/libinnercrossdyadic.f
  ttb/ttb_library.f
Labels: bug

#46 initialisation of tensor components
  CHANGELOG.md
  ttb/ttb_library.f
Labels: enhancement
